name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          chmod 600 ~/.ssh/aws_ec2_key
          ssh-keyscan -H ${{ secrets.AWS_EC2_INSTANCE_IP }} >> ~/.ssh/known_hosts
         
      - name: Install Node.js and npm
        run: |
          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "sudo apt-get update && sudo apt-get install -y nodejs npm"

      - name: Transfer Project to EC2 Instance
        run: |
          scp -i ~/.ssh/aws_ec2_key -r ./* ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }}:/home/ubuntu/web/teste-docker

      - name: Build Docker Image on EC2
        run: |
          scp -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "docker build -t web-app-react-teste /home/ubuntu/web/teste-docker"
  
      - name: Start Docker Container on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "docker run -d -p 80:80 web-app-react-teste"
          

#      - name: Install Serve
#        run: |
#          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "sudo npm install -g serve"

#      - name: Install Dependencies and Build
#        run: |
#          npm install
          

#      - name: Creating folder on EC2
#        run: |
#          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "mkdir -p /home/ubuntu/web/build"

#      - name: Transfer Build to EC2 Instance
#        run: |
#          scp -i ~/.ssh/aws_ec2_key -r build/* ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }}:/home/ubuntu/web/build/


#      - name: Build Docker Image on EC2
#        run: |
#          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "DOCKER_BUILDKIT=1 docker build -t web-app-react-teste /home/ubuntu/web/build"
#          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "docker build -t web-app-react-teste /home/ubuntu/web/build"

  
#      - name: Start Docker Container on EC2
#        run: |
#          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "docker run -d -p 80:80 web-app-react-teste"

#      - name: Start Web Server on EC2
#        run: |
#          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "cd /home/ubuntu/web && serve -s"


name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure SSH Access (using public key)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_PUBLIC_KEY }}" >> ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Transfer Project to EC2 (using SCP)
        run: |
          scp -r -i ~/.ssh/id_rsa.pub <local_project_directory> ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }}:/home/ubuntu/teste-docker

      - name: Install Node.js and npm on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "sudo apt-get update && sudo apt-get install -y nodejs npm"

      - name: Install Dependencies on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "npm install"

      - name: Build Docker Image on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "docker build -t web-app-react-teste /path/to/destination"

      - name: Start Docker Container on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "docker run -d -p 80:80 web-app-react-teste"