name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install SSH Client
        run: sudo apt-get install openssh-client -y

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_EC2_KEY_PAIR }}" > ~/.ssh/aws_ec2_key
          chmod 600 ~/.ssh/aws_ec2_key
          ssh-keyscan -H 44.193.189.111 >> ~/.ssh/known_hosts
          echo "StrictHostKeyChecking no" > ~/.ssh/config

      - name: Install Dependencies
        run: npm install
  
      - name: Build and Package
        run: npm run build

      - name: Creating folder on EC2
        run: |
          ssh -i ~/.ssh/aws_ec2_key ubuntu@${{ secrets.AWS_EC2_INSTANCE_IP }} "mkdir -p /home/ubuntu/web"

      - name: Transfer Build to EC2 Instance
        run: scp -i ~/.ssh/aws_ec2_key -r build/* ubuntu@44.193.189.111:/home/ubuntu/web
  
